name: go_kart
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: 3.3.8

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.0
  circuit_repository:
    path: packages/circuit_repository
  equatable: ^2.0.3
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  get_it: ^7.2.0
  injectable: ^2.0.0
  intl: ^0.17.0
  profile_repository:
    path: packages/profile_repository
  quickalert: ^1.0.1
  supabase_flutter: ^1.2.2

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/logo/round/
    - assets/logo/square/
